name: "Save Build Caches"
description: "Save LTO cache and ccache (both to GH Release) after a build"

inputs:
  build-system:
    required: true
  lto-mode:
    required: true
  lto-asset-name:
    description: "Release asset filename for the LTO cache (only needed when lto-mode is THIN)"
    required: false
  ccache-filename:
    required: true
  gh-token:
    required: true

runs:
  using: composite
  steps:
    - name: "Save LTO Cache"
      if: startsWith(inputs.build-system, 'Make') && inputs.lto-mode == 'THIN'
      uses: ./.github/actions/save-lto-cache
      with:
        asset-name: ${{ inputs.lto-asset-name }}
        gh-token:   ${{ inputs.gh-token }}

    - name: "Save ccache"
      if: always() && startsWith(inputs.build-system, 'Make')
      uses: ./.github/actions/save-caches
      with:
        ccache-filename: ${{ inputs.ccache-filename }}
        gh-token:        ${{ inputs.gh-token }}
